apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-downscaler.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-downscaler.name" . }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - namespaces
  verbs:
    - get
    - watch
    - list
- apiGroups:
    - apps
  resources:
    - deployments
    - statefulsets
  verbs:
    - get
    - watch
    - list
    - update
    - patch
- apiGroups:
    - argoproj.io
  resources:
    - rollouts
  verbs:
    - get
    - watch
    - list
    - update
    - patch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - get
    - watch
    - list
    - update
    - patch
- apiGroups:
    - batch
  resources:
    - cronjobs
  verbs:
    - get
    - watch
    - list
    - update
    - patch
- apiGroups:
    - keda.sh
  resources:
    - scaledobjects
  verbs:
    - get
    - watch
    - list
    - update
    - patch
- apiGroups:
    - zalando.org
  resources:
    - stacks
  verbs:
    - get
    - watch
    - list
    - update
    - patch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - get
    - create
    - watch
    - list
    - update
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-downscaler.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-downscaler.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-downscaler.name" . }}
    namespace: {{ include "kube-downscaler.name" . }}
